param(
  [string]$IpAddress,
  [int]$Port = 3001
)

$ErrorActionPreference = 'Stop'

function Get-ActiveIPv4 {
  $addressFamily = [System.Net.Sockets.AddressFamily]::InterNetwork
  $ignoredNames = @('vEthernet', 'VirtualBox', 'VMware', 'Loopback', 'WSL')

  $candidates = foreach ($adapter in [System.Net.NetworkInformation.NetworkInterface]::GetAllNetworkInterfaces()) {
    if ($adapter.OperationalStatus -ne [System.Net.NetworkInformation.OperationalStatus]::Up) {
      continue
    }

    $description = "$($adapter.Name) $($adapter.Description)"
    if ($ignoredNames | Where-Object { $description -like "*$_*" }) {
      continue
    }

    $properties = $adapter.GetIPProperties()
    $gateway = $properties.GatewayAddresses |
      Where-Object { $_.Address.AddressFamily -eq $addressFamily -and $_.Address.ToString() -ne '0.0.0.0' } |
      Select-Object -First 1

    if (-not $gateway) {
      continue
    }

    $ipv4 = $properties.UnicastAddresses |
      Where-Object { $_.Address.AddressFamily -eq $addressFamily -and $_.Address.ToString() -notlike '169.254.*' } |
      Select-Object -First 1

    if ($ipv4) {
      [pscustomobject]@{
        Adapter = $adapter.Name
        IP = $ipv4.Address.ToString()
        Gateway = $gateway.Address.ToString()
      }
    }
  }

  return $candidates | Select-Object -First 1
}

if (-not $IpAddress) {
  $detected = Get-ActiveIPv4
  if (-not $detected) {
    throw 'Could not detect an active WiFi/LAN IPv4 address. Run ipconfig and pass it manually, for example: npm run network:update -- -IpAddress 192.168.1.50'
  }

  $IpAddress = $detected.IP
  Write-Host "Detected adapter: $($detected.Adapter)"
  Write-Host "Detected gateway: $($detected.Gateway)"
}

if ($IpAddress -notmatch '^\d{1,3}(\.\d{1,3}){3}$') {
  throw "Invalid IPv4 address: $IpAddress"
}

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$projectRoot = Split-Path -Parent $scriptRoot
$configPath = Join-Path $projectRoot 'woodapp-react\src\localNetwork.js'
$timestamp = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ss.fffZ')

$content = @"
// Generated by scripts/update-network.ps1.
// Run ``npm run network:update`` from woodapp-react after changing WiFi/hotspot.
export const LOCAL_NETWORK = {
  serverIp: '$IpAddress',
  serverPort: '$Port',
  updatedAt: '$timestamp',
};
"@

Set-Content -LiteralPath $configPath -Value $content -Encoding utf8

Write-Host ''
Write-Host "Updated $configPath"
Write-Host "Backend URL: http://$IpAddress`:$Port"
Write-Host "Health check: http://$IpAddress`:$Port/api/health"
Write-Host ''
Write-Host 'Next steps:'
Write-Host '1. Start backend: cd backend; npm run dev'
Write-Host '2. Start frontend: cd woodapp-react; npm run dev -- --host 0.0.0.0'
Write-Host "3. On phone browser: http://$IpAddress`:5173"
Write-Host '4. For Android APK: cd woodapp-react; npm run android:refresh-network'
