// Generated by scripts/update-network.ps1.
// Run `npm run network:update` from woodapp-react after changing WiFi/hotspot.
export const LOCAL_NETWORK = {
  serverIp: '10.136.187.103',
  serverPort: '3001',
  updatedAt: '2026-06-06T15:15:47.242Z',
};
