// Generated by scripts/update-network.ps1.
// Run `npm run network:update` from woodapp-react after changing WiFi/hotspot.
export const LOCAL_NETWORK = {
  serverIp: '10.24.57.103',
  serverPort: '3001',
  updatedAt: '2026-06-04T08:31:19.950Z',
};
