// Generated by scripts/update-network.ps1.
// Run `npm run network:update` from woodapp-react after changing WiFi/hotspot.
export const LOCAL_NETWORK = {
  serverIp: '10.253.198.103',
  serverPort: '3001',
  updatedAt: '2026-06-05T10:55:22.371Z',
};
